# Copyright (c) 2021 Nordic Semiconductor ASA
# SPDX-License-Identifier: Apache-2.0

manifest:
  self:
    path: zephyr-caniot-controller

  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos
    - name: zephyrproject-rtos-fork
      url-base: https://github.com/lucasdietrich
      
  projects:
    - name: zephyr
      remote: zephyrproject-rtos-fork
      revision: 764d7f83df4b1d12e1001547bc8f79555fbcb04c
      import: true
      