# Copyright (c) 2021 Nordic Semiconductor ASA
# SPDX-License-Identifier: Apache-2.0

manifest:
  self:
    path: zephyr-caniot-controller

  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos
    - name: zephyrproject-rtos-fork
      url-base: https://github.com/lucasdietrich
      
  projects:
    - name: zephyr
      remote: zephyrproject-rtos-fork
      revision: caniot-controller-v3.7.0 # A project revision can be a branch, tag, or SHA.
      import: true
      