# Copyright (c) 2021 Nordic Semiconductor ASA
# SPDX-License-Identifier: Apache-2.0

manifest:
  self:
    path: zephyr-caniot-controller

  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos
    - name: lucasdietrich
      url-base: https://github.com/lucasdietrich
      

  projects:
    - name: zephyr
      remote: zephyrproject-rtos
      revision: v3.0.0
      import: true
      